name: serene
# include:
#   - base_spec.yml
options:
  bundleIdPrefix: dev.alecrim
# packages:
#   Yams:
#     url: https://github.com/jpsim/Yams
#     from: 2.0.0
targets:
  serene:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [serene]
    info:
      path: serene/Generated/Info.plist
      properties:
        CFBundleDevelopmentRegion: en-US
        CFBundleExecutable: serene
        CFBundleIdentifier: dev.alecrim.serene
        CFBundleName: serene
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: Serene
        UILaunchScreen: {}
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        SWIFT_VERSION: 5.7
      configs:
        debug:
          GENERATE_INFOPLIST_FILE: true
          DEBUG_MODE: true
        release:
          GENERATE_INFOPLIST_FILE: true
          DEBUG_MODE: false